borrowings_service implemented
Yuruch/DRF-Library pull request #6
Opened 2024-08-13 20:47 UTC by DimaYankovskiy

2024-08-13 21:10 UTC, Yuruch requested changes
Thank you for your hard work, but please make some changes :)

2024-08-13 21:10 UTC, Yuruch commented on borrowings_service/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
Borrowing:
Borrow date: date
Expected return date: date
Actual return date: date
Book id: int
User id: int

i guess here should be book id and user id not ForeignKey)

2024-08-13 21:10 UTC, Yuruch commented on borrowings_service/models.py
> +from library_service import settings
settings should be imported only from django.conf

2024-08-13 21:10 UTC, Yuruch commented on borrowings_service/serializers.py
> +        return attrs
Maybe we can just filter books that are not available.
Also expected_return_date should be validated ( > than now)

2024-08-13 21:10 UTC, Yuruch commented on borrowings_service/serializers.py
> +        return value
This validation will never raise ValidationError

2024-08-13 21:10 UTC, Yuruch commented on borrowings_service/views.py
> +    queryset = Borrowing.objects.all()
You don't need queryset  if u redefine get_queryset method

2024-08-13 21:10 UTC, Yuruch commented on borrowings_service/views.py
> +        book.save()
we also will not need this validation if we just filter books

2024-08-13 21:10 UTC, Yuruch commented on borrowings_service/views.py
> +        return Response(serializer.data)
add status code here

2024-08-13 21:13 UTC, Yuruch commented on borrowings_service/models.py
> +    borrow_date = models.DateField(default=datetime.now)
we can use auto_now_add=True here

2024-08-14 07:05 UTC, necobra commented on borrowings_service/admin.py
> +# Register your models here.
maybe just register the model

2024-08-14 07:06 UTC, Yuruch approved these changes
Good job! Thanks for your effort

2024-08-14 07:13 UTC, necobra commented on borrowings_service/views.py
> +        return Response(serializer.data, status=status.HTTP_200_OK)
I see no validation that the same user who took it is returning it. Did you check?

2024-08-14 09:41 UTC, necobra approved these changes

2024-08-14 09:43 UTC, merged